#### create a 2d array with shape (3,3) containing random integers between 1 and 20

In [15]:
import numpy as np

a = np.array([[1,18,5],[15,12,7],[6,19,10]])
a


array([[ 1, 18,  5],
       [15, 12,  7],
       [ 6, 19, 10]])

#### write a numpy program to create a (5,5) array with random values and find the minimum and maximum values for each row

In [20]:
b = np.array([[2,6,9,23,98],[4,19,26,9,17],[10,42,22,34,29],[6,93,12,21,49],[7,13,0,1,50]])
print(f"the largest numbers in each row inside the array : {np.max(b,axis=1)}")

the largest numbers in each row inside the array : [98 26 42 93 50]


#### write a numpy program to create a random vector of size 10 and sort it 

In [37]:
ar = np.random.rand(10)
sorted_ar = np.sort(ar)
print(f"{sorted_ar}")

[0.16836323 0.21602789 0.3844959  0.4889088  0.60268961 0.66946674
 0.69328854 0.7006848  0.84696959 0.97947196]


#### write a numpy program to find the most frequent value in array 

In [45]:
ab =np.array([1,17,86,17,8,1,17,5,86,1,17,9])
ab_list = ab.tolist()
big_count = 0
freq = 0
for num in ab_list :
    count = ab_list.count(num)
    if count > big_count :
        big_count = count
        freq = num 
    else : 
        continue 
    
print(f"{freq}")

17


#### replace all even numbers in the 2d array with 0

In [48]:
arr = np.array([[1,16,14],[3,7,9],[20,17,11]])
arr[arr%2==0]=0
arr

array([[ 1,  0,  0],
       [ 3,  7,  9],
       [ 0, 17, 11]])

#### apply the square root function to each element of the 1d array 

In [50]:
c = np.array([9,4,16,81,16])
sqrt_c= np.sqrt(c)
print(f"{sqrt_c}")

[3. 2. 4. 9. 4.]


#### write a numpy program to create a 3*3 array with random values and subtract the mean of each row from each element

In [66]:
d = np.array([[1,3,5],[2,6,4],[1,7,10]])
ndx = 0 
mean_arr = np.array([])
for row in d : 
    mean_arr = np.insert(mean_arr,ndx,np.mean(d[ndx]))
    ndx+=1
#for ndx,row in enumerate(d) : 
    #mean_arr = np.insert(mean_arr,ndx,np.mean(row))
for mean_num in mean_arr :
    for num in d :
        print(f"{mean_num} - {num} = {mean_num - num}")

3.0 - [1 3 5] = [ 2.  0. -2.]
3.0 - [2 6 4] = [ 1. -3. -1.]
3.0 - [ 1  7 10] = [ 2. -4. -7.]
4.0 - [1 3 5] = [ 3.  1. -1.]
4.0 - [2 6 4] = [ 2. -2.  0.]
4.0 - [ 1  7 10] = [ 3. -3. -6.]
6.0 - [1 3 5] = [5. 3. 1.]
6.0 - [2 6 4] = [4. 0. 2.]
6.0 - [ 1  7 10] = [ 5. -1. -4.]


#### create a 1d array containing the first 20 odd numbers 

In [70]:
odd_arr = np.array([])
ndx=0
for num in range (20):
    if num %2!= 0:
        odd_arr= np.insert(odd_arr,ndx,num)
        ndx+=1
    else :
        continue    
print(f"{odd_arr}")
    

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


#### write a numpy program to create a 5*5 array with random values and find the second-largest value in each column

In [75]:
arr5=np.array([[1,6,4,19,0],[13,6,7,23,0],[11,29,33,10,2],[7,13,64,15,22],[13,9,44,18,44]])
sorted_ar5=np.sort(arr5,axis=0)
print(sorted_ar5)
print(f" the second largest number in each column : {sorted_ar5[3,:]}")

[[ 1  6  4 10  0]
 [ 7  6  7 15  0]
 [11  9 33 18  2]
 [13 13 44 19 22]
 [13 29 64 23 44]]
 the second largest number in each column : [13 13 44 19 22]


#### write a numpy program to create a 4*4 array with random values and find the sum of each row 

In [78]:
array = np.array([[2,5,4,6],[17,1,10,3],[5,7,8,3],[13,2,6,15]])
ndx=0
for row in range (4):
    sum = np.sum(array[ndx])
    ndx+=1
    print(f"sum of raw {ndx} = {sum}")
    

sum of raw 1 = 17
sum of raw 2 = 31
sum of raw 3 = 23
sum of raw 4 = 36
